-- =========================================================
-- FILE SEED DATA AKAR KATA UNTUK EXPO SQLITE (PRE-POPULATE DUMP)
-- =========================================================

INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('qala', 'ق', 'و', 'ل', 'Berkata / Berucap / Berbicara', 1, '', 'قَؤُولٌ', 'Ajwaf', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nadda', 'ن', 'د', 'د', 'Melarikan diri / kabur / menjauh / ganjil (Kamus Munawwir, Lisanul ''Arab)', 2, '', 'نَدِيدٌ / نَدٌّ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nazza', 'ن', 'ز', 'ز', 'Memancar / menetes / melompat / gelisah (Kamus Munawwir, Lisanul ''Arab)', 2, '', 'نَزِيزٌ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nassa', 'ن', 'س', 'س', 'Mengeringkan / menjadi kering / menggiring (Kamus Munawwir, Lisanul ''Arab)', 1, '', 'نَسِيسٌ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nasysya', 'ن', 'ش', 'ش', 'Mengering / menghalau burung / mendidih (Kamus Munawwir, Lisanul ''Arab)', 1, '', 'نَشِيشٌ / نَشَّاشٌ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nashsha', 'ن', 'ص', 'ص', 'Menegaskan / menyusun teks / menaikkan / menentukan (Kamus Munawwir, Lisanul ''Arab)', 1, '', 'نَصِيصٌ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nadhdha', 'ن', 'ض', 'ض', 'Menetes air / memancar perlahan / menguangkan barang (Kamus Munawwir, Lisanul ''Arab)', 2, '', 'نَضِيضٌ / نَضَّاضٌ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('naththa', 'ن', 'ط', 'ط', 'Melompat / meloncat / meregangkan (Kamus Munawwir, Lisanul ''Arab)', 1, '', 'نَطِيطٌ / نَطَّاطٌ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('naffa', 'ن', 'ف', 'ف', 'Meniup hidung / bersin / meremahkan (Kamus Munawwir, Lisanul ''Arab)', 2, '', 'نَفِيفٌ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('naqqa', 'ن', 'ق', 'ق', 'Berbunyi (katak) / berkotek (ayam) / mengerik (Kamus Munawwir, Lisanul ''Arab)', 1, '', 'نَقِيقٌ / نَقَّاقٌ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('namma', 'ن', 'م', 'م', 'Mengadu domba / memfitnah / menghias (Kamus Munawwir, Lisanul ''Arab)', 1, '', 'نَمِيمٌ / نَمُومٌ', 'Mudho''af', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nafada', 'ن', 'ف', 'د', 'Habis / punah / berakhir / habis persediaan (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 4, '', 'نَفِدٌ / نَفِيدٌ', 'Shohih', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nafadha', 'ن', 'ف', 'ذ', 'Menembus / berlaku / melaksanakan / tembus (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 1, '', 'نَفِيذٌ', 'Shohih', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nafara', 'ن', 'ف', 'ر', 'Lari / menjauh / bubar / berangkat perang (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 1, '', 'نَفِيرٌ / نَفُورٌ', 'Shohih', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nafasa', 'ن', 'ف', 'س', 'Menjadi berharga / bernilai tinggi / kikir (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 5, '', 'نَفِيسٌ', 'Shohih', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nafa_a', 'ن', 'ف', 'ع', 'Bermanfaat / memberi guna / berguna (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 3, '', 'نَفِيعٌ / نَفِعٌ', 'Shohih', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nafaqa', 'ن', 'ف', 'ق', 'Laris (barang) / habis / berkurang / mati (hewan) (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 1, '', 'نَفِيقٌ / نَفِقٌ', 'Shohih', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('nafay', 'ن', 'ف', 'ي', 'Meniadakan / menolak / membuang / mengusir (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 2, '', 'نَفِيٌّ', 'Naqis', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('naqaba', 'ن', 'ق', 'ب', 'Melubangi / menembus dinding / menjadi pemimpin (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 1, '', 'نَقِيبٌ', 'Shohih', '');
INSERT OR REPLACE INTO dictionary (id, fa, ain, lam, translation, bab_num, explanation, sifat_musyabihat, bina, asal) VALUES ('naqaha', 'ن', 'ق', 'ح', 'Merevisi / memperbaiki karangan / memotong dahan (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 3, '', 'نَقِيحٌ / نَقِحٌ', 'Shohih', '');

-- Seeding Data Favorit Terpilih
INSERT OR REPLACE INTO favorites (id, fa, ain, lam, translation, bab_num, notes, custom, ai_explanation) VALUES ('maqqa', 'م', 'ق', 'ق', 'Membuka mulut lebar / mencintai / tinggi (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 1, 'Tersimpan Otomatis: Jamak Sifat Musyabihat Tidak Standard', 0, '');
INSERT OR REPLACE INTO favorites (id, fa, ain, lam, translation, bab_num, notes, custom, ai_explanation) VALUES ('matta_ta', 'م', 'ط', 'ط', 'Meregangkan / memanjangkan / menarik (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 1, 'Tersimpan Otomatis: Jamak Sifat Musyabihat Tidak Standard', 0, '');
INSERT OR REPLACE INTO favorites (id, fa, ain, lam, translation, bab_num, notes, custom, ai_explanation) VALUES ('massa_sad', 'م', 'ص', 'ص', 'Menghisap / menyedot air (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 4, 'Tersimpan Otomatis: Jamak Sifat Musyabihat Tidak Standard', 0, '');
INSERT OR REPLACE INTO favorites (id, fa, ain, lam, translation, bab_num, notes, custom, ai_explanation) VALUES ('mashsha', 'م', 'ش', 'ش', 'Memeras / menyerap / menghisap (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 1, 'Tersimpan Otomatis: Jamak Sifat Musyabihat Tidak Standard', 0, '');
INSERT OR REPLACE INTO favorites (id, fa, ain, lam, translation, bab_num, notes, custom, ai_explanation) VALUES ('massa', 'م', 'س', 'س', 'Menyentuh / meraba / menimpa musibah (Kamus Munawwir, Al-Munjid, Lisanul ''Arab)', 4, 'Tersimpan Otomatis: Memiliki Sifat Musyabihat & Masdar > 1', 0, '');
