name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: stable

      - name: Fix gradlew permission
        run: |
          git config core.fileMode true
          git update-index --chmod=+x android/gradlew
          chmod +x android/gradlew

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release --no-pub

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: al-qomus-premium-apk
          path: build/app/outputs/flutter-apk/app-release.apk
