name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci --include=dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Memanggil token dengan aman
        
      - name: Build project
        run: npm run build
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/
